version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-test
    ports:
      - "8081:8081"
    volumes:
      - ./ssl:/app/ssl
    restart: always